### ISSUE TITLE
docker pull buildbarn/bb-event-service fails

### ISSUE THREAD

**Issue by martopad** [buildbarn/bb-event-service#5]
I even tried "docker pull docker.io/buildbarn/bb-event-service"

Error Message:
``` 
"Using default tag: latest
Error response from daemon: manifest for buildbarn/bb-event-service:latest not found: manifest unknown: manifest unknown"
```
At first I thought because i am under proxy but I am able to pull "hello-world" just fine.

Tried this on both windows and linux
Docker Windows: 2.1.0(36874) (19.03) 
Docker Linux: Docker version 19.03.0, build aeac9490dc

**Comment by mickael-carl** [comment]
Hi! This is because you don't specify a tag, so docker defaults to `latest`, as the first line mentions: `"Using default tag: latest`. However we do not publish such a tag:
```bash
$ curl -L -s 'https://registry.hub.docker.com/v2/repositories/buildbarn/bb-event-service/tags?page_size=1024'|jq '."results"[]["name"]'
"20190727T185731Z-eeaf75c"
"20190617T160116Z-3ab3681"
"20190227T204225Z-1b8e1b0"
"20190225T222112Z-b9170c2"
```

Using that first tag in the list:
```bash
$ docker pull buildbarn/bb-event-service:20190727T185731Z-eeaf75c
20190727T185731Z-eeaf75c: Pulling from buildbarn/bb-event-service
4109819def68: Pull complete
Digest: sha256:d6559a73e1f3eafd3068ffd8f387ea74709ca9f45b11c01fe04c2f0cf2d7af08
Status: Downloaded newer image for buildbarn/bb-event-service:20190727T185731Z-eeaf75c
docker.io/buildbarn/bb-event-service:20190727T185731Z-eeaf75c
```
Just works®

**Comment by martopad** [comment]
Oh, I didn't know that. It works for me also. Thank you for the help!
